# Generated by Django 6.0.3 on 2026-03-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
