# Generated by Django 6.0.3 on 2026-03-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_career_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['-posted_on']},
        ),
        migrations.AddField(
            model_name='career',
            name='is_open',
            field=models.BooleanField(default=True, help_text='True = accepting applications. False = position filled/closed.'),
        ),
    ]
