# Generated by Django 6.0.3 on 2026-03-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('published_on', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
        ),
    ]
