# Generated by Django 6.0.3 on 2026-03-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='passwordresettoken',
            table='password_reset_tokens',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
