# Generated by Django 6.0.3 on 2026-03-15 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_last_changed',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the password was last set or changed'),
        ),
    ]
