# Generated by Django 6.0.3 on 2026-03-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact_messages',
        ),
    ]
