export { default as DashboardPage }   from "./Dashboard/DashboardPage"
//export { default as LoginPage }       from "./Auth/LoginPage"
export { default as ServicesList }    from "./Services/ServicesList"
//export { default as UsersList }       from "./Users/UsersList"
export { default as HomepageEditor }  from "./Homepage/HomepageEditor"
//export { default as teamsList }    from "./pages/teamsList"
export { default as TeamsList } from "./Team/Teamslist"