# Generated by Django 6.0.3 on 2026-03-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('banner_text', models.CharField(blank=True, max_length=200, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('stats_title', models.CharField(blank=True, max_length=200, null=True)),
                ('stats_value', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
