# Generated by Django 6.0.3 on 2026-03-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_homepage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about',
            field=models.JSONField(blank=True, default=dict, help_text='About section: title, subtitle, description, image, founded, team_size'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_section',
            field=models.JSONField(blank=True, default=dict, help_text='Contact section: title, email, phone, address, map_link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects_section',
            field=models.JSONField(blank=True, default=dict, help_text='Projects showcase section: title, subtitle, items[]'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_section',
            field=models.JSONField(blank=True, default=dict, help_text='Services overview section: title, subtitle, items[]'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='tech_stack',
            field=models.JSONField(blank=True, default=dict, help_text='Tech stack section: title, subtitle, items[]'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_section',
            field=models.JSONField(blank=True, default=dict, help_text='Testimonials section: title, subtitle, items[]'),
        ),
        migrations.AlterModelTable(
            name='homepage',
            table='homepage',
        ),
    ]
