# Generated by Django 6.0.3 on 2026-03-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testimonial',
            table='testimonials',
        ),
    ]
