# Generated by Django 6.0.3 on 2026-03-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=100)),
                ('completed_on', models.DateField()),
                ('project_image', models.ImageField(blank=True, null=True, upload_to='projects/screenshots/')),
            ],
        ),
    ]
