# Generated by Django 6.0.3 on 2026-03-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-completed_on']},
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web_mobile', 'Web & Mobile'), ('ai_ml', 'AI & ML'), ('data_engineering', 'Data Engineering'), ('cloud_devops', 'Cloud & DevOps'), ('iot', 'IoT'), ('enterprise', 'Enterprise'), ('other', 'Other')], default='other', help_text='Used for dashboard grouping chart', max_length=50),
        ),
    ]
