# Generated by Django 6.0.3 on 2026-03-15 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. Lead Developer, UI Designer', max_length=100)),
                ('department', models.CharField(help_text='e.g. Engineering, Design, Marketing', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Profile photo shown on website', null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True, help_text='Short bio shown on the team page')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Inactive members are hidden from public website', max_length=10)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower number = appears first. 0 = top of list.')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Social links as JSON: {linkedin, github, twitter, ...}')),
                ('joined', models.DateField(blank=True, help_text='Date they joined the company', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, help_text='Link to admin login account. Optional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_members',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
